spring.application.name=Site
server.port=8080

jwt.secret=secret_key_ap_anime_divisor
jwt.expiration=3
jwt.refresh=15

# RABBITMQ - funcionar sem Docker (local)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

# SQLite Config
spring.datasource.url=jdbc:sqlite:anime.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Execute o schema.sql toda vez
spring.sql.init.mode=always

# Desativar JPA/Hibernate se está usando JDBC
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.validation=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always
spring.mvc.throw-exception-if-no-handler-found=true



